apiVersion: v1
kind: Pod
metadata:
        name: httpbin 
spec:
        containers:
        - name: httpbin
          image: registry.dev.rafay-edge.net:5000/azhou/httpbin:andy-non-http
        imagePullSecrets:
        - name: rcloud-registry-creds 

