apiVersion: v1
kind: ReplicationController
metadata:
  name: udp-server
  labels:
    app: udp-server
spec:
  replicas: 5
  selector:
    app: udp-server
  template:
    metadata:
      name: udp-server
      labels:
        app: udp-server
    spec:
      containers:
      - image: rafay-udp-server
        command:
          - ./rafay-udp-server
        imagePullPolicy: IfNotPresent
        name: rafy-udp-server
      restartPolicy: Always
