apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ipvs-controller
  namespace: kube-system
  labels:
    k8s-app: ipvs-controller
spec:
  selector:
    matchLabels:
      name: ipvs-controller
  template:
    metadata:
      labels:
        name: ipvs-controller
    spec:
      containers:
      - name: ipvs-controller
        image: registry.dev.rafay-edge.net:5000/azhou/ipvs-controller:andy-non-http-20190301-1412
        securityContext:
                capabilities:
                        add: [ "NET_ADMIN" ]

