apiVersion: "ipvscontroller.rep.net/v1"
kind: Ipvs
metadata:
        name: ipvs-rule
spec:
        name: "ipvs-workload-1"
        type: "l4port"
        portspec:
          lbtype: "RR"
          nat: "yes"
          protocol: "udp"
          public:
             ip: "1.2.3.4"
             port: 6666
          internals:
                  -:
                    ip: "192.168.0.100"
                    port: 1234
                  -:
                    ip: "192.168.0.101"
                    port: 1235
